<!DOCTYPE html>
<html>
<head>
	<title>实验</title>
	<meta charset="utf-8">
	<style type="text/css">
		*{margin:0px;padding:0px;}
		#head{

			background: rgba(255,255,2,0.5);width: 100%;height: 150px;
		}

		#in{
			background: rgba(0,0,0,0.5);width: 100%;height: 50px;
		}
		li{
			float: left;
		}
		

	</style>
</head>
<body>

	<div id="head"></div>
	<div id="in">
		<ul class="lise">
			<li>首页</li>
			<li>首页</li>
			<li>首页</li>
			<li>首页</li>
			<li>首页</li>

		</ul>

	</div>




</body>
</html>
